### PR TITLE
fix: ignore warnings in publishing

### LINKED ISSUE #46: PUBLISHED_WITH_FRICTION_WARNING makes semantic-release-chrome fail
# Issue

- [x] I have searched the [issues](https://github.com/GabrielDuarteM/semantic-release-chrome/issues) of this repository and believe that this is not a duplicate.

## Your Environment

- `semantic-release-chrome` version: https://github.com/exKAZUu/semantic-release-chrome (v1.1.1 with #44)
- `node` version: v10.16.3
- `yarn` version: 1.17.3

## What you did and problem description

When publishing my extension (https://github.com/WillBooster/plantuml-visualizer/), PUBLISHED_WITH_FRICTION_WARNING occurs and it makes `semantic-release-chrome` fail.

## What happened

Here is the log.

```
[1:55:45 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #229: https://github.com/WillBooster/plantuml-visualizer/issues/229.
[1:55:55 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] › ✖  PUBLISHED_WITH_FRICTION_WARNING Your item needs extra time to review because your item has all hosts permission.
{ AggregateError: 
    SemanticReleaseError: Your item needs extra time to review because your item has all hosts permission.
        at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:62:19)
    at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:66:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Reproduction repository/CodeSandbox

https://github.com/WillBooster/plantuml-visualizer/

## Suggested solution

`semantic-release-chrome` should just ignore `PUBLISHED_WITH_FRICTION_WARNING` because this warning is not problematic for releasing extensions.

### PR DESCRIPTION
**Pull request by exKAZUu**
# Pull Request

## Related issue

Close #46 
Include #44

## Description

This PR makes this plugin ignores warnings given by Chrome Web Store.

## Why

Actually, extensions are published even if warnings occur.

## How

This PR makes this plugin ignores warnings whose status code contains `WARNING`.

## Screenshots

```
[1:55:45 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #229: https://github.com/WillBooster/plantuml-visualizer/issues/229.
[1:55:55 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] › ✖  PUBLISHED_WITH_FRICTION_WARNING Your item needs extra time to review because your item has all hosts permission.
{ AggregateError: 
    SemanticReleaseError: Your item needs extra time to review because your item has all hosts permission.
        at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:62:19)
    at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:66:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## How has this been tested

I've tested my fork (https://github.com/exKAZUu/semantic-release-chrome) including this patch by published my extension using the fork.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Documentation
- [x] Ready to be merged 
- [x] My code follows the code style of this project (run `npm run ci` to be sure).
- [x] I have read the **[CONTRIBUTING](https://github.com/GabrielDuarteM/semantic-release-chrome/blob/master/CONTRIBUTING.md)** document.

### CODE REVIEW

**Comment by GabrielDuarteM** [comment]
Hi @exKAZUu! Thank you for another PR!

I was looking for this PUBLISHED_WITH_FRICTION_WARNING on google, but it doesn't seem very common, mostly it pointed to another extension which had also this problem, and I couldn't find anything about that warning on the webstore api docs... It seems to be related to when the extension gets into a review process, did that happen to you as well?

If it is because of the review thing, the extension probably would not available for download right away (correct me if I'm wrong), so we should probably display a message to inform that to the user so that it doesn't get unnoticed.

File: src/publish.ts [hunk 1]
```diff
@@ -55,12 +56,18 @@ const publish = async ({ extensionId, target, asset }: PluginConfig) => {
   if (!publishRes.status.includes('OK')) {
     const errors: SemanticReleaseError[] = []
     for (let i = 0; i < publishRes.status.length; i += 1) {
-      const message = publishRes.statusList[i]
       const code = publishRes.status[i]
-      const err = new SemanticReleaseError(message, code)
-      errors.push(err)
+      const message = publishRes.statusDetail[i]
+      if (code.includes('WARNING')) {
```
Comment (GabrielDuarteM) [inline src/publish.ts]: According to the [publish API](https://developer.chrome.com/webstore/webstore_api/items/publish#response), `code` can only be one of the following:

* NOT_AUTHORIZED
* INVALID_DEVELOPER
* DEVELOPER_NO_OWNERSHIP
* DEVELOPER_SUSPENDED
* ITEM_NOT_FOUND
* ITEM_PENDING_REVIEW
* ITEM_TAKEN_DOWN
* PUBLISHER_SUSPENDED

Are you sure that `code` can also be `PUBLISHED_WITH_FRICTION_WARNING`?

Also, I think it would be better to have some sort of error whitelist array to check, instead of checking directly against the `code` variable, something like 

```js
const errorWhitelist = ['PUBLISHED_WITH_FRICTION_WARNING']

const publish = async [...] {
	[...]
	if (errorWhitelist.includes(code)) {
}
```

File: src/publish.ts [hunk 2]
```diff
@@ -55,12 +56,18 @@ const publish = async ({ extensionId, target, asset }: PluginConfig) => {
...
+        logger.log('%s: %s', code, message)
```
Comment (GabrielDuarteM) [inline src/publish.ts]: I think it would be more readable to use template literals instead:
```suggestion
        logger.log(`${code}: ${message}`)
```

**Comment by exKAZUu** [comment]
@GabrielDuarteM 

Thank you for taking your time!

> I was looking for this PUBLISHED_WITH_FRICTION_WARNING on google, but it doesn't seem very common, mostly it pointed to another extension which had also this problem, and I couldn't find anything about that warning on the webstore api docs... It seems to be related to when the extension gets into a review process, did that happen to you as well?

Yes. When publishing our extension (https://github.com/WillBooster/plantuml-visualizer), we always face `PUBLISHED_WITH_FRICTION_WARNING` because our extension has broad permissions (https://github.com/WillBooster/plantuml-visualizer/blob/master/manifest.json#L14-L23).
As you understand, this warning indicates Google takes just a long time to review our extension and our extension will be released after 5-10 days.

> Are you sure that code can also be PUBLISHED_WITH_FRICTION_WARNING?

Yes, I'm sure. We always receive this warning in `code` variable and then the current implementation (without this PR) fails.

> If it is because of the review thing, the extension probably would not available for download right away (correct me if I'm wrong), so we should probably display a message to inform that to the user so that it doesn't get unnoticed.

This PR shows the following message so I think it's enough.

```
PUBLISHED_WITH_FRICTION_WARNING: Your item needs extra time to review because your item has all hosts permission.
```

**Comment by exKAZUu** [comment]
FYI: we are using now my fork (https://github.com/exKAZUu/semantic-release-chrome/blob/master/src/publish.ts) as a temporal workaround and I confirmed this worked well.

File: src/publish.ts [hunk 3]
```diff
@@ -55,12 +61,18 @@ const publish = async ({ extensionId, target, asset }: PluginConfig) => {
   if (!publishRes.status.includes('OK')) {
     const errors: SemanticReleaseError[] = []
     for (let i = 0; i < publishRes.status.length; i += 1) {
-      const message = publishRes.statusDetail[i]
       const code = publishRes.status[i]
-      const err = new SemanticReleaseError(message, code)
-      errors.push(err)
+      const message = publishRes.statusDetail[i]
+      if (errorWhitelist.includes(code)) {
+        logger.log(`${code}: ${message}`)
```
Comment (GabrielDuarteM) [inline src/publish.ts]: Maybe we should use `warn` instead, I think it would raise more visibility for the message...

```suggestion
        logger.warn(`${code}: ${message}`)
```

**Comment by GabrielDuarteM** [comment]
@exKAZUu Fair enough, it's unfortunate (and a bit weird) that this is not on their docs, but anyway, I left just a small last comment on the PR, and overall it LGTM :)

**Comment by exKAZUu** [comment]
Hmm, the current type definition doesn't include `logger.warn`. I will check whether `logger.warn` exists in `semantic-release` or not at first.

**Comment by GabrielDuarteM** [comment]
Yesterday I took a quick look at their code, it seems that they use `warn` here https://github.com/semantic-release/semantic-release/blob/7a939a897097a730f1579002ed641a583d3381c4/index.js#L29

It seems that they use [signale](https://github.com/klaussinani/signale) to create the logger, which has the warn variant, so I guess its just a matter of adding it to the typings

**Comment by exKAZUu** [comment]
Thanks! I've added the type definition.

**Comment by GabrielDuarteM** [comment]
Thanks a lot for the PR!
